# Generated by Django 3.2.4 on 2021-07-07 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='startdate',
            new_name='start_date',
        ),
    ]
