# Generated by Django 3.2.4 on 2021-06-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotisation_amount', models.DecimalField(decimal_places=2, default=500, max_digits=7)),
                ('start_date', models.DateField()),
            ],
        ),
    ]
